[package]
name = "okfx_graph"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
okfx_parser = { path = "../okfx_parser" }
okfx_resolver = { path = "../okfx_resolver" }
serde = { version = "1.0", features = ["derive"] }
